const titles={cours:'Comprendre le cours',exercices:'Refaire les exercices',formules:'Les formules',tp:'Packet Tracer',sources:'Supports & suite'};
const lessons=[...document.querySelectorAll('.lesson')];
function route(){let s=lessons.find(s=>s.id===(location.hash.slice(1)||'c-reperes'))||lessons[0];lessons.forEach(x=>x.hidden=x!==s);document.querySelectorAll('.mode-nav a').forEach(a=>{const active=a.dataset.group===s.dataset.group;a.classList.toggle('active',active);active?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});document.getElementById('breadcrumb').textContent=titles[s.dataset.group];document.getElementById('chapter-label').textContent=titles[s.dataset.group];const list=lessons.filter(x=>x.dataset.group===s.dataset.group),links=document.getElementById('chapter-links');links.replaceChildren();list.forEach(x=>{const a=document.createElement('a');a.href='#'+x.id;a.textContent=x.querySelector('h2').textContent;a.classList.toggle('active',x===s);if(x===s)a.setAttribute('aria-current','page');links.append(a)});const bottom=document.getElementById('page-bottom'),i=list.indexOf(s);bottom.replaceChildren();for(const [label,x] of [['Précédent',list[i-1]],['Continuer',list[i+1]]])if(x){const a=document.createElement('a');a.href='#'+x.id;a.className='page-link '+(label==='Continuer'?'next':'previous');const icon=document.createElement('span');icon.className='page-arrow';icon.setAttribute('aria-hidden','true');icon.textContent=label==='Continuer'?'→':'←';const text=document.createElement('span');text.className='page-link-text';const direction=document.createElement('span');direction.className='page-direction';direction.textContent=label;const title=document.createElement('strong');title.className='page-title';title.textContent=x.querySelector('h2').textContent;text.append(direction,title);a.append(icon,text);bottom.append(a)}document.title=s.querySelector('h2').textContent+' · Réseaux';closeMenu();window.scrollTo({top:0,left:0,behavior:'instant'})}
const sidebar=document.getElementById('sidebar'),menuButton=document.querySelector('.menu-button'),backdrop=document.getElementById('menu-backdrop'),mainPane=document.querySelector('.main');
function closeMenu(restoreFocus=false){const wasOpen=sidebar.classList.contains('open');sidebar.classList.remove('open');menuButton.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');backdrop.hidden=true;mainPane.inert=false;if(wasOpen&&restoreFocus)menuButton.focus()}
function openMenu(){sidebar.classList.add('open');menuButton.setAttribute('aria-expanded','true');document.body.classList.add('menu-open');backdrop.hidden=false;mainPane.inert=true;document.querySelector('.menu-close').focus()}
document.querySelector('.menu-close').addEventListener('click',()=>closeMenu(true));backdrop.addEventListener('click',()=>closeMenu(true));sidebar.addEventListener('click',e=>{if(e.target.closest('a')){closeMenu();document.getElementById('main').focus({preventScroll:true})}});
window.matchMedia('(max-width:760px)').addEventListener('change',e=>{if(!e.matches)closeMenu()});
document.querySelectorAll('.diagram-svg').forEach(svg=>{const w=document.createElement('div');w.className='diagram-scroll';w.tabIndex=0;w.setAttribute('role','region');w.setAttribute('aria-label','Schéma : faire défiler horizontalement sur téléphone');const hint=document.createElement('p');hint.className='diagram-hint';hint.textContent='↔ Fais glisser le schéma pour tout voir';svg.before(hint,w);w.append(svg);svg.style.setProperty('--diagram-width',svg.viewBox.baseVal.width+'px')});
document.querySelectorAll('table').forEach(t=>{if(t.parentElement.classList.contains('table-wrap'))return;const w=document.createElement('div');w.className='table-wrap';w.tabIndex=0;w.setAttribute('role','region');w.setAttribute('aria-label','Tableau : faire défiler si nécessaire');t.before(w);w.append(t)});
window.addEventListener('hashchange',route);menuButton.addEventListener('click',()=>sidebar.classList.contains('open')?closeMenu(true):openMenu());document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu(true);if(e.key==='Tab'&&sidebar.classList.contains('open')){const items=[...sidebar.querySelectorAll('a,button')],first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const layerCopy={4:'TCP ajoute les ports et les informations utiles à un échange fiable. Le résultat est un segment TCP.',3:'IPv4 ajoute notamment les IP source et destination, le TTL et les champs de fragmentation. Le résultat est un paquet IPv4.',2:'Ethernet ajoute les adresses MAC pour le lien local et un FCS en fin de trame. Le résultat est une trame Ethernet.'};document.querySelectorAll('[data-layer]').forEach(b=>b.addEventListener('click',()=>{const box=b.closest('.diagram');box.querySelectorAll('[data-layer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));box.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('selected',x.dataset.level===b.dataset.layer));box.querySelector('.layer-explain').textContent=layerCopy[b.dataset.layer]}));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(headers,rows)=>'<div class="table-wrap" tabindex="0" role="region" aria-label="Résultat du calcul"><table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
const error=(el,msg)=>el.innerHTML='<p class="error">'+esc(msg)+'</p>';
function fragment(total,mtu){if(!Number.isInteger(total)||total<20||total>65535||!Number.isInteger(mtu)||mtu<28||mtu>65535)throw Error('Entre une longueur totale entière de 20 à 65 535 et une MTU entière de 28 à 65 535 octets.');if(total<=mtu)return [{fragment:1,data:total-20,total,offset:0,mf:0}];const max=8*Math.floor((mtu-20)/8),data=total-20,out=[];let sent=0;while(sent<data){const size=Math.min(max,data-sent);out.push({fragment:out.length+1,data:size,total:size+20,offset:sent/8,mf:sent+size<data?1:0});sent+=size}return out}
function updateFragment(total,mtu){const el=document.getElementById('fragment-result');try{const r=fragment(total,mtu),shown=r.length>80?[...r.slice(0,5),...r.slice(-3)]:r;el.innerHTML='<p><strong>'+r.length+' '+(r.length>1?'fragments':'paquet')+'</strong> · Données initiales : '+(total-20)+' octets. '+(r.length===1?'Le paquet tient dans la MTU.':'Maximum non final : '+r[0].data+' octets de données.')+'</p>'+table(['Fragment','Données (octets)','Total IPv4','Offset','MF'],shown.map(x=>[x.fragment,x.data,x.total,x.offset,x.mf]))+(shown.length<r.length?'<p class="caption">Tableau abrégé : les cinq premiers et les trois derniers fragments.</p>':'')+'<p class="caption">Vérification : somme des données = '+r.reduce((s,x)=>s+x.data,0)+' octets ; chaque paquet ≤ '+mtu+' octets. Surcharge supplémentaire : '+20*(r.length-1)+' octets.</p>';return r}catch(e){error(el,e.message);throw e}}
document.getElementById('fragment-form')?.addEventListener('submit',e=>{e.preventDefault();try{updateFragment(Number(document.getElementById('frag-total').value),Number(document.getElementById('frag-mtu').value))}catch{}});
function checksum(words){let sum=0,steps=[];for(const w of words){sum+=w;const raw=sum;while(sum>65535)sum=(sum&65535)+(sum>>>16);steps.push([hex(w),raw.toString(16).toUpperCase(),hex(sum)])}return {sum,checksum:(~sum)&65535,steps}}const hex=n=>n.toString(16).toUpperCase().padStart(4,'0');
document.getElementById('checksum-form')?.addEventListener('submit',e=>{e.preventDefault();const el=document.getElementById('checksum-result'),parts=document.getElementById('checksum-input').value.trim().split(/[\s,;]+/);if(parts.length>100||!parts.every(w=>/^(0x)?[0-9a-f]{1,4}$/i.test(w))){error(el,'Entre de 1 à 100 mots hexadécimaux, chacun de 1 à 4 chiffres (0 à 9, A à F).');return}const r=checksum(parts.map(w=>parseInt(w.replace(/^0x/i,''),16)));el.innerHTML=table(['Mot ajouté','Somme avant report','Somme sur 16 bits'],r.steps)+'<div class="result">Somme reportée = <strong>0x'+hex(r.sum)+'</strong><br>Checksum = <strong>0x'+hex(r.checksum)+'</strong><br>Contrôle : '+hex(r.sum)+' + '+hex(r.checksum)+' = FFFF</div>'});
function divideCRC(bits,g){let a=[...bits].map(Number),b=[...g].map(Number),steps=[];for(let i=0;i<=a.length-b.length;i++)if(a[i]===1){const aligned='0'.repeat(i)+g+'0'.repeat(a.length-i-b.length);for(let j=0;j<b.length;j++)a[i+j]^=b[j];steps.push({aligned,after:a.join('')})}return {remainder:a.slice(-(g.length-1)).join(''),steps}}
function updateCRC(d,g){const el=document.getElementById('crc-result');if(!/^[01]{1,64}$/.test(d)||!/^1[01]{0,15}1$/.test(g)){error(el,'D doit contenir 1 à 64 bits ; G doit contenir 2 à 17 bits et commencer et finir par 1.');throw Error('Données CRC invalides')}const r=g.length-1,padded=d+'0'.repeat(r),c=divideCRC(padded,g),frame=d+c.remainder,check=divideCRC(frame,g);el.innerHTML='<p>Degré r = '+r+' ; on divise <code>'+padded+'</code> par <code>'+g+'</code>.</p><details class="solution"><summary>Voir les XOR successifs</summary><pre>'+esc(padded+'\n'+c.steps.map(s=>s.aligned+'  XOR\n'+s.after).join('\n'))+'</pre></details><div class="result">CRC : <strong>'+c.remainder+'</strong><br>Trame envoyée : <code>'+frame+'</code><br>Reste à la réception : <strong>'+check.remainder+'</strong></div>';return {crc:c.remainder,frame,receiverRemainder:check.remainder}}
document.getElementById('crc-form')?.addEventListener('submit',e=>{e.preventDefault();try{updateCRC(document.getElementById('crc-data').value.trim(),document.getElementById('crc-gen').value.trim())}catch{}});
function aloha(n,p){return n*p*Math.pow(1-p,n-1)}
function updateAloha(){const n=Number(document.getElementById('aloha-n').value),p=Number(document.getElementById('aloha-p').value),el=document.getElementById('aloha-result');if(!Number.isInteger(n)||n<1||n>200){error(el,'Choisis un nombre entier de stations entre 1 et 200.');return}const fmt=n=>n.toLocaleString('fr-FR',{maximumFractionDigits:3}),s=aloha(n,p),idle=Math.pow(1-p,n),collision=Math.max(0,1-idle-s);document.getElementById('aloha-p-value').textContent=fmt(p);el.innerHTML='N = '+n+', p = '+fmt(p)+' : <strong>'+fmt(s*100)+' % de succès</strong>.<br>Créneaux vides : '+fmt(idle*100)+' % · Collisions : '+fmt(collision*100)+' %.<br>Maximum à p = 1/'+n+' = '+fmt(1/n)+' : <strong>'+fmt(aloha(n,1/n)*100)+' %</strong>.';const xmax=Math.min(1,4/n),ymax=n===1?1:.55,x=v=>55+v/xmax*605,y=v=>195-v/ymax*160;let path='';for(let i=0;i<=240;i++){const p=xmax*i/240;path+=(i?'L':'M')+x(p).toFixed(2)+' '+y(aloha(n,p)).toFixed(2)}document.getElementById('aloha-chart').innerHTML='<path d="M55 25V195H660" fill="none" stroke="#94a8c3" stroke-width="1.5"/><g font-size="13" fill="#526479"><text x="10" y="35">'+(ymax*100).toFixed(0)+' %</text><text x="25" y="200">0</text><text x="54" y="220">0</text><text x="580" y="220">p = '+fmt(xmax)+'</text><text x="80" y="24">Efficacité S(p)</text></g><path d="'+path+'" fill="none" stroke="#225ce0" stroke-width="3"/><line x1="'+x(1/n)+'" x2="'+x(1/n)+'" y1="35" y2="195" stroke="#087964" stroke-dasharray="5 4"/>'+(p<=xmax?'<circle cx="'+x(p)+'" cy="'+y(s)+'" r="6" fill="#05a6b9" stroke="white" stroke-width="2"/>':'')+'<text x="'+(Math.min(x(1/n)+8,565))+'" y="55" font-size="13" fill="#087964">p optimal</text>'}
document.getElementById('aloha-n')?.addEventListener('input',updateAloha);document.getElementById('aloha-p')?.addEventListener('input',updateAloha);document.getElementById('aloha-opt')?.addEventListener('click',()=>{const n=Number(document.getElementById('aloha-n').value);if(Number.isInteger(n)&&n>0&&n<=200){document.getElementById('aloha-p').value=1/n;updateAloha()}});
document.querySelectorAll('[data-vlan-action]').forEach(b=>b.addEventListener('click',()=>{const box=b.closest('.diagram'),broadcast=b.dataset.vlanAction==='broadcast';box.querySelector('.vlan-explain').textContent=broadcast?'PC1 diffuse dans le VLAN 10 : PC2, PC3, PC7 et PC8 reçoivent le broadcast. Le VLAN 20 ne le reçoit pas. Le trunk transporte cette diffusion entre S1 et S2.':'PC1 et PC4 sont dans deux VLAN et deux sous-réseaux différents. PC1 transmet à sa passerelle ; le routeur émet une nouvelle trame dans le VLAN 20 vers PC4. Le trunk seul ne réalise pas ce routage.';box.querySelectorAll('.vlan-ee,.vlan-trunk').forEach(x=>{x.style.stroke='#225ce0';x.style.strokeWidth='5'});box.querySelectorAll('.vlan-cs').forEach(x=>{x.style.opacity=broadcast?'.2':'1';x.style.strokeWidth=broadcast?'3':'5'});box.querySelector('.vlan-routing').style.opacity=broadcast?'.15':'1';box.querySelectorAll('[data-vlan-action]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}));
const states=[
{fixed:[],dist:[0,'∞','∞','∞','∞','∞'],edges:[],text:'Initialisation : A = 0 ; les autres distances valent ∞. Aucun sommet fixé.'},
{fixed:['A'],dist:[0,4,2,'∞','∞','∞'],edges:['AB','AC'],text:'On fixe A (0). On propose B = 4 et C = 2 ; leur prédécesseur est A.'},
{fixed:['A','C'],dist:[0,3,2,10,12,'∞'],edges:['AC','BC','CD','CE'],text:'On fixe C (2). B : min(4, 2+1) = 3 ; D = 10 ; E = 12. Leur prédécesseur devient C.'},
{fixed:['A','C','B'],dist:[0,3,2,8,12,'∞'],edges:['AC','BC','BD','CE'],text:'On fixe B (3). D : min(10, 3+5) = 8. Le prédécesseur de D devient B.'},
{fixed:['A','C','B','D'],dist:[0,3,2,8,10,14],edges:['AC','BC','BD','DE','DF'],text:'On fixe D (8). E : min(12, 8+2) = 10 ; F = 8+6 = 14. Leur prédécesseur devient D.'},
{fixed:['A','C','B','D','E'],dist:[0,3,2,8,10,13],edges:['AC','BC','BD','DE','EF'],text:'On fixe E (10). F : min(14, 10+3) = 13. Le prédécesseur de F devient E.'},
{fixed:['A','C','B','D','E','F'],dist:[0,3,2,8,10,13],edges:['AC','BC','BD','DE','EF'],text:'On fixe F (13). Chemin A → C → B → D → E → F, coût 2+1+5+2+3 = 13.'}
];let step=0;
function updateDijkstra(){const box=document.getElementById('dijkstra-demo');if(!box)return;const s=states[step];box.querySelectorAll('[data-node]').forEach(x=>{x.style.fill=s.fixed.includes(x.dataset.node)?'#b9f0f2':'white';x.style.strokeWidth=x.dataset.node===s.fixed.at(-1)?'4':'2'});box.querySelectorAll('[data-edge]').forEach(x=>{x.style.stroke=s.edges.includes(x.dataset.edge)?'#225ce0':'#b1bfd2';x.style.strokeWidth=s.edges.includes(x.dataset.edge)?'4':'3'});document.getElementById('dijkstra-state').innerHTML='<p>'+s.text+'</p>'+table(['A','B','C','D','E','F'],[s.dist])+'<p class="caption">Sommets fixés : '+(s.fixed.join(', ')||'aucun')+'. Bleu : prédécesseurs retenus à cette étape.</p>';document.getElementById('dijkstra-counter').textContent='Étape '+step+' / 6';document.getElementById('dijkstra-prev').disabled=step===0;document.getElementById('dijkstra-next').disabled=step===6}
document.getElementById('dijkstra-prev')?.addEventListener('click',()=>{step=Math.max(0,step-1);updateDijkstra()});document.getElementById('dijkstra-next')?.addEventListener('click',()=>{step=Math.min(6,step+1);updateDijkstra()});document.getElementById('dijkstra-reset')?.addEventListener('click',()=>{step=0;updateDijkstra()});
route();if(document.getElementById('aloha-n'))updateAloha();updateDijkstra();
if(document.modelContext?.registerTool){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'calculate_fragmentation',title:'Calculer les fragments IPv4',description:'Ouvre la fiche formules et calcule les fragments visibles du paquet IPv4. DF=0 ; en-tête sans options de 20 octets.',inputSchema:{type:'object',properties:{total:{type:'integer',minimum:20,maximum:65535},mtu:{type:'integer',minimum:28,maximum:65535}},required:['total','mtu'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['total','mtu'].includes(k)))throw Error('Paramètres invalides');fragment(input.total,input.mtu);document.getElementById('frag-total').value=input.total;document.getElementById('frag-mtu').value=input.mtu;location.hash='f-formules';route();const r=updateFragment(input.total,input.mtu);document.getElementById('fragment-lab').scrollIntoView();return {count:r.length,fragments:r.length<=80?r:[...r.slice(0,5),...r.slice(-3)]}}},{signal:life.signal})).catch(()=>{})}catch{}window.addEventListener('pagehide',()=>life.abort(),{once:true})}
